#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 jumakonana
# SPDX-License-Identifer: BSD-3-Clause


import sys

i = n = ans = size = 0

if sys.stdin.isatty():
    sys.exit(1)

lines = sys.stdin.readlines()


for line in lines:
    size += 1


rem = size % 2


for line in lines:
    try:
        n = int(line)
    except:
        try:
            n = float(line)    
        except ValueError:
            sys.exit(1)
    
    i += 1

    if rem == 0:
        if i == size / 2:
            ans = n
        if i == (size / 2) + 1:
            ans = (ans + n) / 2
    else:
        if i == (size / 2) + 0.5:
            ans = n


print(ans)
